% The synthetic chaotic signals were generated by the popular logistic map equation x[n + 1] =
% ?x[n] × (1 ? x[n]) (Sprott and Sprott 2003), which shows chaotic behaviour for 3.54 < ? < 4. In this work, the
% value of ? is chosen as 4 and the initial value of x[n] is selected randomly between 0 and 1 for each realization of
% the signal. Two periodic signals, a sine wave and a triangular wave, were used. They were digitized at a sa


function [x] = getLogisticMap(mu,N)

   x=nan(N,1);
   
   x(1,1)=rand();
   
   for i=2:N
       x(i,1)=(mu*x(i-1,1))*(1-x(i-1,1));
   end
   
end

