  probability = [];
  %dataStrt = 0;
  dataStrt = 1;
  %dataWind = 1;
  dataWind = 2;
  dataSkip = 1;
  dataReps = 1;
  scale = 1;   %// scale to use for downsampling
  dataMax = 0;
  dataMin = 0;
  mean = 0;
  variance = 0;
  stdev = 0;
  skew = 0;
  kurt = 0;
  verbose = 0;
  last_pattern = 0;
  last_tolerance = 0.0;
  outSize = DEFAULT_OUTSIZE;
  outType = 0;   %// do nothing